package org.firstinspires.ftc.teamcode.pedro;

import com.pedropathing.algorithm.Foresight;
import com.pedropathing.algorithm.ForesightConfig;
import com.pedropathing.follower.Follower;
// Used by the configuration generated by AutoTune.
import com.pedropathing.controllers.Controller;
import com.pedropathing.math.Matrix;
import com.pedropathing.math.Vector2D;
import com.pedropathing.revhub.drivetrains.Mecanum;
import com.pedropathing.revhub.drivetrains.MecanumConfig;
import com.pedropathing.revhub.localizers.PinpointConfig;
import com.pedropathing.revhub.localizers.PinpointLocalizer;
import com.qualcomm.hardware.gobilda.GoBildaPinpointDriver;
import com.qualcomm.robotcore.hardware.DcMotor;
import com.qualcomm.robotcore.hardware.DcMotorSimple;
import com.qualcomm.robotcore.hardware.HardwareMap;
import org.firstinspires.ftc.robotcore.external.navigation.DistanceUnit;

/** TRIONIX hardware settings. Recheck directions and offsets on the current robot. */
public final class Constants {
    private Constants() { }

    public static final String INTAKE_NAME = "Intake Motor";
    public static final double INTAKE_POWER = 0.5;

    public static MecanumConfig drivetrainConfig = new MecanumConfig(c -> {
        c.frontLeftName.set("Front Left Motor");
        c.backLeftName.set("Back Left Motor");
        c.frontRightName.set("Front Right Motor");
        c.backRightName.set("Back Right Motor");
        c.frontLeftDirection.set(DcMotorSimple.Direction.REVERSE);
        c.backLeftDirection.set(DcMotorSimple.Direction.REVERSE);
        c.frontRightDirection.set(DcMotorSimple.Direction.FORWARD);
        c.backRightDirection.set(DcMotorSimple.Direction.FORWARD);
        c.manualBrakeMode.set(true);
    });

    // From main at be0e16d; verify with the Pinpoint tuner before Foresight tuning.
    // xPodOffset is the forward pod's lateral offset (old forwardPodY).
    // yPodOffset is the strafe pod's longitudinal offset (old strafePodX).
    public static PinpointConfig localizerConfig = new PinpointConfig(c -> {
        c.name.set("pinpoint");
        c.podType.set(GoBildaPinpointDriver.GoBildaOdometryPods.goBILDA_4_BAR_POD);
        c.xPodOffset.set(7.555415836844857);
        c.yPodOffset.set(-7.442356019508182);
        c.xPodDirection.set(GoBildaPinpointDriver.EncoderDirection.REVERSED);
        c.yPodDirection.set(GoBildaPinpointDriver.EncoderDirection.FORWARD);
        c.globalDistanceUnit.set(DistanceUnit.INCH);
        c.offsetUnits.set(DistanceUnit.INCH);
    });

    // Replace this declaration with the complete Java output from Foresight AutoTune.
    // Old Pedro 2 PID/braking values are not compatible tuning data.
    public static ForesightConfig foresightConfig = new ForesightConfig(
            c -> {
                Controller primaryTranslationalForward = Controller.proportional(0.16544775106525855);
                Controller secondaryTranslationalForward = Controller.proportional(0.0611285231732847);
                Controller primaryTranslationalLateral = Controller.proportional(0.2088102974131572);
                Controller secondaryTranslationalLateral = Controller.proportional(0.07714982538025533);

                c.forwardTranslational.set(Controller.piecewise(secondaryTranslationalForward).put(2.5, primaryTranslationalForward));
                c.strafeTranslational.set(Controller.piecewise(secondaryTranslationalLateral).put(2.5, primaryTranslationalLateral));

                c.coast.set(Controller.proportionalFeedforward(0.01741282811951234));
                c.brake.set(Controller.proportionalFeedforward(0.014800903901585487));

                c.headingFeedback.set(Controller.proportional(3.220948077615023));
                c.headingBrakeCoefficients.set(Vector2D.cartesian(0.049189149525470995, 0.004403334383226634));

                c.linearBrakeCoefficients.set(Matrix.diag(0.06677489745788398, 0.05874895519890594));
                c.quadraticBrakeCoefficients.set(Matrix.diag(9.084534428333848E-4, 0.0010302045040525656));

                c.maxAchievableForwardVelocity.set(59.85176006543063);
                c.maxAchievableStrafeVelocity.set(53.01385162079252);
                c.naturalForwardDeceleration.set(34.05303189795054);
                c.naturalStrafeDeceleration.set(53.5017844135203);
            }
    );


    public static boolean isTuned() {
        return foresightConfig != null;
    }

    public static Mecanum createDrivetrain(HardwareMap hardwareMap) {
        String[] names = {drivetrainConfig.frontLeftName.get(), drivetrainConfig.frontRightName.get(),
                drivetrainConfig.backLeftName.get(), drivetrainConfig.backRightName.get()};
        for (String name : names) {
            DcMotor motor = hardwareMap.get(DcMotor.class, name);
            motor.setPower(0);
            motor.setMode(DcMotor.RunMode.RUN_WITHOUT_ENCODER);
        }
        return new Mecanum(hardwareMap, drivetrainConfig);
    }

    public static PinpointLocalizer createLocalizer(HardwareMap hardwareMap) {
        return new PinpointLocalizer(hardwareMap, localizerConfig);
    }

    public static Follower create(HardwareMap hardwareMap) {
        if (!isTuned()) {
            throw new IllegalStateException("Run Foresight AutoTune and paste its configuration into Constants.java first.");
        }
        return new Follower(createLocalizer(hardwareMap), createDrivetrain(hardwareMap),
                new Foresight(foresightConfig));
    }
}
