package org.firstinspires.ftc.teamcode.pedro;

import com.pedropathing.algorithm.Foresight;
import com.pedropathing.algorithm.ForesightConfig;
import com.pedropathing.follower.Follower;
// Used by the configuration generated by AutoTune.
import com.pedropathing.controllers.Controller;
import com.pedropathing.math.Matrix;
import com.pedropathing.math.Vector2D;
import com.pedropathing.revhub.drivetrains.Mecanum;
import com.pedropathing.revhub.drivetrains.MecanumConfig;
import com.pedropathing.revhub.localizers.PinpointConfig;
import com.pedropathing.revhub.localizers.PinpointLocalizer;
import com.qualcomm.hardware.gobilda.GoBildaPinpointDriver;
import com.qualcomm.robotcore.hardware.DcMotor;
import com.qualcomm.robotcore.hardware.DcMotorSimple;
import com.qualcomm.robotcore.hardware.HardwareMap;
import org.firstinspires.ftc.robotcore.external.navigation.DistanceUnit;

/** TRIONIX hardware settings. Recheck directions and offsets on the current robot. */
public final class Constants {
    private Constants() { }

    public static final String INTAKE_NAME = "Intake Motor";
    public static final double INTAKE_POWER = 0.5;

    public static MecanumConfig drivetrainConfig = new MecanumConfig(c -> {
        c.frontLeftName.set("Front Left Motor");
        c.backLeftName.set("Back Left Motor");
        c.frontRightName.set("Front Right Motor");
        c.backRightName.set("Back Right Motor");
        c.frontLeftDirection.set(DcMotorSimple.Direction.REVERSE);
        c.backLeftDirection.set(DcMotorSimple.Direction.REVERSE);
        c.frontRightDirection.set(DcMotorSimple.Direction.FORWARD);
        c.backRightDirection.set(DcMotorSimple.Direction.FORWARD);
        c.manualBrakeMode.set(true);
    });

    // From main at be0e16d; verify with the Pinpoint tuner before Foresight tuning.
    // xPodOffset is the forward pod's lateral offset (old forwardPodY).
    // yPodOffset is the strafe pod's longitudinal offset (old strafePodX).
    public static PinpointConfig localizerConfig = new PinpointConfig(c -> {
        c.name.set("pinpoint");
        c.podType.set(GoBildaPinpointDriver.GoBildaOdometryPods.goBILDA_4_BAR_POD);
        c.xPodOffset.set(-7.6043422428641705);
        c.yPodOffset.set(0.9393324964628462);
        c.xPodDirection.set(GoBildaPinpointDriver.EncoderDirection.REVERSED);
        c.yPodDirection.set(GoBildaPinpointDriver.EncoderDirection.FORWARD);
        c.globalDistanceUnit.set(DistanceUnit.INCH);
        c.offsetUnits.set(DistanceUnit.INCH);
    });

    // Replace this declaration with the complete Java output from Foresight AutoTune.
    // Old Pedro 2 PID/braking values are not compatible tuning data.
    public static ForesightConfig foresightConfig = null;

    public static boolean isTuned() {
        return foresightConfig != null;
    }

    public static Mecanum createDrivetrain(HardwareMap hardwareMap) {
        String[] names = {drivetrainConfig.frontLeftName.get(), drivetrainConfig.frontRightName.get(),
                drivetrainConfig.backLeftName.get(), drivetrainConfig.backRightName.get()};
        for (String name : names) {
            DcMotor motor = hardwareMap.get(DcMotor.class, name);
            motor.setPower(0);
            motor.setMode(DcMotor.RunMode.RUN_WITHOUT_ENCODER);
        }
        return new Mecanum(hardwareMap, drivetrainConfig);
    }

    public static PinpointLocalizer createLocalizer(HardwareMap hardwareMap) {
        return new PinpointLocalizer(hardwareMap, localizerConfig);
    }

    public static Follower create(HardwareMap hardwareMap) {
        if (!isTuned()) {
            throw new IllegalStateException("Run Foresight AutoTune and paste its configuration into Constants.java first.");
        }
        return new Follower(createLocalizer(hardwareMap), createDrivetrain(hardwareMap),
                new Foresight(foresightConfig));
    }
}
